from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse

from app.core.templates import templates
from app.services.converter_data_service import ConverterDataService
from app.services.language_service import LanguageService
from app.services.public_seo_service import build_public_page_seo

router = APIRouter(prefix="/tools", tags=["tools"])
converter_data_service = ConverterDataService(Path("app/data/converters"))
language_service = LanguageService(Path("app/locales"))


def _build_tool_page_sections(tool_data: dict[str, Any]) -> dict[str, Any]:
    source = (tool_data.get("source") or "file").upper()
    target = (tool_data.get("target") or "output").upper()
    source_name = (tool_data.get("source") or "file").lower()
    target_name = (tool_data.get("target") or "output").lower()

    hero = tool_data.get("hero") or {}
    if not isinstance(hero, dict):
        hero = {}
    hero_data = {
        "eyebrow": "Converter tool",
        "title": tool_data.get("title", "File Converter"),
        "description": tool_data.get("description", ""),
        "panel_label": "Ready to convert",
        "panel_title": "Upload one file and get your converted result.",
    }
    hero_data.update(hero)

    benefits = tool_data.get("benefits") or []
    if not benefits:
        benefits = []

    features = tool_data.get("features") or []
    if not features and benefits:
        features = [
            {"title": item.get("title", "Fast conversion"), "text": item.get("text", "")}
            for item in benefits
        ]
    if not features:
        features = [
            {
                "title": "Fast conversion",
                "text": f"Convert {source_name} files to {target_name} quickly and securely.",
            },
            {
                "title": "Simple workflow",
                "text": "Upload your file, choose the output, and receive the result in seconds.",
            },
            {
                "title": "Reliable output",
                "text": "Get a polished conversion result ready for download or sharing.",
            },
        ]

    supported_formats = tool_data.get("supported_formats") or {}
    if not supported_formats:
        supported_formats = {
            "input": [source] if source else [],
            "output": [target] if target else [],
            "description": f"{source} input, {target} output",
        }
    elif isinstance(supported_formats, list):
        supported_formats = {"input": supported_formats, "output": [], "description": ""}

    how_to_use = tool_data.get("how_to_use") or []
    if not how_to_use:
        how_to_use = [
            {
                "title": "Upload your file",
                "description": f"Select a {source_name} file to begin the conversion.",
            },
            {
                "title": "Choose output",
                "description": f"Pick {target_name} as the result format and review the options.",
            },
            {
                "title": "Download instantly",
                "description": "Get your converted file without installing extra software.",
            },
        ]

    use_cases = tool_data.get("use_cases") or []
    if not use_cases:
        use_cases = [
            f"Use this {source_name} to {target_name} workflow for everyday file sharing.",
            f"Prepare {source_name} files for compatibility with modern {target_name} workflows.",
            f"Optimize content pipelines that need a reliable {target_name} output.",
        ]

    about_formats = tool_data.get("about_formats") or []
    if not about_formats:
        about_formats = [
            {
                "title": f"What is {source_name.upper()}?",
                "text": f"{source_name.upper()} is the source format used in this conversion flow.",
            },
            {
                "title": f"What is {target_name.upper()}?",
                "text": f"{target_name.upper()} is the output format generated by this conversion tool.",
            },
        ]

    cta = tool_data.get("cta") or {}
    if not isinstance(cta, dict):
        cta = {}
    cta_data = {
        "eyebrow": "Ready to convert",
        "title": f"Convert {source_name} files to {target_name} in seconds.",
        "text": "Upload your file and receive the converted result instantly.",
        "primary_text": "Convert now",
        "secondary_text": "Read FAQs",
        "primary_href": "#converter",
        "secondary_href": "#faq",
    }
    cta_data.update(cta)

    return {
        "hero": hero_data,
        "benefits": benefits,
        "features": features,
        "supported_formats": supported_formats,
        "how_to_use": how_to_use,
        "use_cases": use_cases,
        "about_formats": about_formats,
        "cta": cta_data,
    }


TOOL_DIRECTORY_CATEGORIES = {
    "image": {
        "title": "Image tools",
        "description": "Convert photos and graphic assets for editing, publishing, and compatibility.",
        "icon": "🖼️",
    },
    "document": {
        "title": "Document tools",
        "description": "Transform PDFs, office files, and text documents with fast, reliable workflows.",
        "icon": "📄",
    },
    "audio": {
        "title": "Audio tools",
        "description": "Convert music and voice files into MP3, WAV, and other common audio formats.",
        "icon": "🎧",
    },
    "archive": {
        "title": "Archive tools",
        "description": "Extract, inspect, and manage compressed archives with one-click access.",
        "icon": "📦",
    },
}


def _normalize_directory_category(tool: dict[str, Any]) -> str | None:
    category = str(tool.get("category", "") or "").strip().lower()
    if category == "pdf":
        category = "document"
    if category not in TOOL_DIRECTORY_CATEGORIES:
        category = str(tool.get("output_category", "") or "").strip().lower()
    if category == "pdf":
        category = "document"
    if category not in TOOL_DIRECTORY_CATEGORIES:
        return None
    return category


def _sort_tools_for_directory(tool: dict[str, Any]) -> tuple[int, int, str]:
    return (
        0 if tool.get("featured") else 1,
        0 if tool.get("popular") else 1,
        str(tool.get("title", "")).lower(),
    )


def _build_tools_directory_categories() -> list[dict[str, Any]]:
    converters = converter_data_service.list_supported_converters()
    grouped: dict[str, list[dict[str, Any]]] = {key: [] for key in TOOL_DIRECTORY_CATEGORIES}
    for tool in converters:
        category = _normalize_directory_category(tool)
        if not category:
            continue
        grouped[category].append(tool)

    category_list: list[dict[str, Any]] = []
    for slug, definition in TOOL_DIRECTORY_CATEGORIES.items():
        tools = sorted(grouped[slug], key=_sort_tools_for_directory)[:5]
        if not tools:
            continue
        category_list.append({
            "slug": slug,
            "title": definition["title"],
            "description": definition["description"],
            "icon": definition["icon"],
            "tools": tools,
        })

    return category_list


async def render_universal_tool_page(
    request: Request,
    slug: str,
    canonical_path: str | None = None,
    meta_overrides: dict[str, str] | None = None,
    faq_items: list[dict[str, str]] | None = None,
) -> HTMLResponse:
    locale_data = language_service.load_locale(
        accept_language=request.headers.get("accept-language"),
        lang_query=request.query_params.get("lang"),
    )

    def t(key: str, default: str = "") -> str:
        return language_service.translate(locale_data, key, default)

    try:
        tool_data = converter_data_service.load_converter_by_slug(slug)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Tool page not found")

    canonical_path = canonical_path or f"/tools/{slug}"
    hero = (tool_data.get("hero") or {}) if isinstance(tool_data.get("hero"), dict) else {}
    base_title = str(tool_data.get("title") or f"{slug.replace('-', ' ').title()} Converter").strip()
    if slug == "mp4-to-mp3":
        title = "MP4 to MP3 | Converigo"
    elif slug in {"pdf-to-jpg", "png-to-jpg"}:
        title = f"{base_title} Online Free" if base_title else "Converter Online Free"
    else:
        title = f"{base_title} Online Free - Converigo" if base_title else "Converter Online Free - Converigo"

    source = str(tool_data.get("source") or "").strip()
    target = str(tool_data.get("target") or "").strip()
    if slug == "mp4-to-mp3":
        description = "Convert MP4 to MP3 Online Free"
    elif source == "pdf" and target in {"jpg", "jpeg"}:
        description = "Convert PDF files to JPG images online free"
    elif source == "png" and target == "jpg":
        description = "Convert PNG images to JPG online free"
    else:
        description = tool_data.get("seo", {}).get("description") or tool_data.get("description") or "Convert files online with Converigo."

    faq_source = list(faq_items or tool_data.get("faq") or [])
    label = str(tool_data.get("title") or "this").replace(" Converter", "").strip()
    if not faq_source:
        faq_source = [
            {"question": f"What is {label or 'this'} conversion?", "answer": f"Use this tool to convert {label or 'files'} quickly and securely."},
            {"question": f"How do I convert {tool_data.get('source', 'file').upper()} to {tool_data.get('target', 'output').upper()}?", "answer": "Upload your file, choose the output format, and download the converted result."},
            {"question": f"Is {label or 'this'} converter free?", "answer": "Yes, this converter is free to use for standard conversion tasks."},
        ]
    else:
        faq_source = [
            {"question": f"What is {label or 'this'} conversion?", "answer": f"Use this tool to convert {label or 'files'} quickly and securely."},
            {"question": f"Is {label or 'this'} converter free?", "answer": "Yes, this converter is free to use for standard conversion tasks."},
            *faq_source,
        ]

    related = []
    for item in tool_data.get("related_tools") or []:
        if isinstance(item, dict):
            related.append({
                "slug": item.get("slug") or "",
                "title": item.get("title") or item.get("slug") or "Related tool",
                "description": item.get("description") or "Discover another useful conversion flow.",
            })
        elif isinstance(item, str):
            related.append({"slug": item, "title": item.replace('-', ' ').title(), "description": "Discover another useful conversion flow."})

    if not related:
        related = [
            {"slug": "pdf-to-jpg", "title": "PDF to JPG", "description": "Convert PDF pages into JPG images for sharing and editing."},
            {"slug": "jpg-to-png", "title": "JPG to PNG", "description": "Create transparent or high-quality PNG images from JPG inputs."},
        ]

    page_sections = _build_tool_page_sections(tool_data)
    if slug == "mp4-to-mp3":
        page_sections["how_to_use"] = [
            {"title": "Upload your MP4 file", "description": "Select an MP4 video from your device to begin the conversion."},
            {"title": "Convert to MP3", "description": "Choose MP3 as the output format and extract the audio quickly."},
            {"title": "Download your converted MP3", "description": "Get your converted MP3 file instantly for listening or sharing."},
        ]
    seo = build_public_page_seo(
        canonical_path,
        title,
        description,
        schema_type="WebPage",
        breadcrumbs=[
            {"name": "Home", "url": "/"},
            {"name": "Tools", "url": "/tools"},
            {"name": title, "url": canonical_path},
        ],
        faq_items=faq_source,
    )
    seo_data = seo["meta"]
    if meta_overrides:
        seo_data.update(meta_overrides)

    return templates.TemplateResponse(
        request=request,
        name="tool_page.html",
        context={
            "request": request,
            "locale": locale_data,
            "t": t,
            "title": seo_data["title"],
            "meta": seo_data,
            "page_hreflang_base": seo_data.get("canonical"),
            "seo": seo_data,
            "tool": tool_data,
            "faq": faq_source,
            "upload_form": tool_data.get("upload_form", {}),
            "related_tools": related,
            "structured_data": seo["structured_data"],
            "hero": page_sections["hero"],
            "benefits": page_sections["benefits"],
            "features": page_sections["features"],
            "supported_formats": page_sections["supported_formats"],
            "how_to_use": page_sections["how_to_use"],
            "use_cases": page_sections["use_cases"],
            "about_formats": page_sections["about_formats"],
            "cta": page_sections["cta"],
            "landing": {"h1": page_sections["hero"].get("title"), "breadcrumb": [{"name": "Home", "url": "/"}, {"name": "Tools", "url": "/tools"}, {"name": title, "url": canonical_path}]},
        },
    )


@router.get("", response_class=HTMLResponse)
async def tools_index(request: Request):
    locale_data = language_service.load_locale(
        accept_language=request.headers.get("accept-language"),
        lang_query=request.query_params.get("lang"),
    )

    def t(key: str, default: str = "") -> str:
        return language_service.translate(locale_data, key, default)

    categories = _build_tools_directory_categories()
    seo = build_public_page_seo(
        "/tools",
        "Tools Directory | Converigo",
        "Browse Converigo converters by category with fast access to image, document, audio, and archive tools.",
        schema_type="WebPage",
        keywords="tools directory, file converters, image conversion, document conversion, audio conversion, archive tools",
        breadcrumbs=[
            {"name": "Home", "url": "/"},
            {"name": "Tools", "url": "/tools"},
        ],
    )

    return templates.TemplateResponse(
        request=request,
        name="pages/tools_directory.html",
        context={
            "request": request,
            "locale": locale_data,
            "t": t,
            "supported_locales": language_service.get_supported_locales(),
            "meta": seo["meta"],
            "page_hreflang_base": seo["meta"].get("canonical"),
            "categories": categories,
            "structured_data": seo["structured_data"],
            "year": datetime.utcnow().year,
        },
    )


@router.get("/{slug}", response_class=HTMLResponse)
async def tool_page(request: Request, slug: str):
    return await render_universal_tool_page(request, slug, canonical_path=f"/tools/{slug}")
