from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse

from app.core.templates import templates
from app.services.converter_data_service import ConverterDataService
from app.services.language_service import LanguageService
from app.services.landing_service import LandingPageBuilder
from app.services.seo_service import PRODUCTION_BASE_URL, SeoService

router = APIRouter(prefix="/tools", tags=["tools"])
converter_data_service = ConverterDataService(Path("app/data/converters"))
seo_service = SeoService(Path("app/data/converters"))
landing_page_builder = LandingPageBuilder(seo_service, converter_data_service)
language_service = LanguageService(Path("app/locales"))


def _build_tool_page_sections(tool_data: dict[str, Any]) -> dict[str, Any]:
    source = (tool_data.get("source") or "file").upper()
    target = (tool_data.get("target") or "output").upper()
    source_name = (tool_data.get("source") or "file").lower()
    target_name = (tool_data.get("target") or "output").lower()

    hero = tool_data.get("hero") or {}
    if not isinstance(hero, dict):
        hero = {}
    hero_data = {
        "eyebrow": "Converter tool",
        "title": tool_data.get("title", "File Converter"),
        "description": tool_data.get("description", ""),
        "panel_label": "Ready to convert",
        "panel_title": "Upload one file and get your converted result.",
    }
    hero_data.update(hero)

    benefits = tool_data.get("benefits") or []
    if not benefits:
        benefits = []

    features = tool_data.get("features") or []
    if not features and benefits:
        features = [
            {"title": item.get("title", "Fast conversion"), "text": item.get("text", "")}
            for item in benefits
        ]
    if not features:
        features = [
            {
                "title": "Fast conversion",
                "text": f"Convert {source_name} files to {target_name} quickly and securely.",
            },
            {
                "title": "Simple workflow",
                "text": "Upload your file, choose the output, and receive the result in seconds.",
            },
            {
                "title": "Reliable output",
                "text": "Get a polished conversion result ready for download or sharing.",
            },
        ]

    supported_formats = tool_data.get("supported_formats") or {}
    if not supported_formats:
        supported_formats = {
            "input": [source] if source else [],
            "output": [target] if target else [],
            "description": f"{source} input, {target} output",
        }
    elif isinstance(supported_formats, list):
        supported_formats = {"input": supported_formats, "output": [], "description": ""}

    how_to_use = tool_data.get("how_to_use") or []
    if not how_to_use:
        how_to_use = [
            {
                "title": "Upload your file",
                "description": f"Select a {source_name} file to begin the conversion.",
            },
            {
                "title": "Choose output",
                "description": f"Pick {target_name} as the result format and review the options.",
            },
            {
                "title": "Download instantly",
                "description": "Get your converted file without installing extra software.",
            },
        ]

    use_cases = tool_data.get("use_cases") or []
    if not use_cases:
        use_cases = [
            f"Use this {source_name} to {target_name} workflow for everyday file sharing.",
            f"Prepare {source_name} files for compatibility with modern {target_name} workflows.",
            f"Optimize content pipelines that need a reliable {target_name} output.",
        ]

    about_formats = tool_data.get("about_formats") or []
    if not about_formats:
        about_formats = [
            {
                "title": f"What is {source_name.upper()}?",
                "text": f"{source_name.upper()} is the source format used in this conversion flow.",
            },
            {
                "title": f"What is {target_name.upper()}?",
                "text": f"{target_name.upper()} is the output format generated by this conversion tool.",
            },
        ]

    cta = tool_data.get("cta") or {}
    if not isinstance(cta, dict):
        cta = {}
    cta_data = {
        "eyebrow": "Ready to convert",
        "title": f"Convert {source_name} files to {target_name} in seconds.",
        "text": "Upload your file and receive the converted result instantly.",
        "primary_text": "Convert now",
        "secondary_text": "Read FAQs",
        "primary_href": "#converter",
        "secondary_href": "#faq",
    }
    cta_data.update(cta)

    return {
        "hero": hero_data,
        "benefits": benefits,
        "features": features,
        "supported_formats": supported_formats,
        "how_to_use": how_to_use,
        "use_cases": use_cases,
        "about_formats": about_formats,
        "cta": cta_data,
    }


async def render_universal_tool_page(
    request: Request,
    slug: str,
    canonical_path: str | None = None,
    meta_overrides: dict[str, str] | None = None,
    faq_items: list[dict[str, str]] | None = None,
) -> HTMLResponse:
    locale_data = language_service.load_locale(
        accept_language=request.headers.get("accept-language"),
        lang_query=request.query_params.get("lang"),
    )

    def t(key: str, default: str = "") -> str:
        return language_service.translate(locale_data, key, default)

    try:
        tool_data = converter_data_service.load_converter_by_slug(slug)
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Tool page not found")

    if slug == "mp4-to-mp3":
        landing = landing_page_builder.build_context(
            request,
            tool_data,
            faq_items=faq_items,
            canonical_path=canonical_path,
        )
        seo_data = landing["meta"]
        related_tools = landing["related_tools"]
        faq_items = landing["faq"]
    else:
        seo_data = seo_service.build_tool_meta(request, tool_data)
        related_tools = converter_data_service.resolve_related_tools(tool_data, limit=4)

    fallback_faq = []
    label = tool_data.get("title", "").replace(" Converter", "").strip()
    slug = tool_data.get("slug", "")
    if label:
        fallback_faq = [
            {
                "question": f"What is {label} conversion?",
                "answer": f"Use this tool to convert {label} files quickly and securely.",
            },
            {
                "question": f"How do I convert {label}?",
                "answer": "Upload your file, choose the output format, and download the converted result.",
            },
            {
                "question": f"Is {label} converter free?",
                "answer": "Yes, this converter is free to use for standard conversion tasks.",
            },
            {
                "question": f"Why convert {label}?",
                "answer": f"Converting {label} helps improve compatibility, sharing, and workflow automation.",
            },
        ]
        if slug.endswith("-png") or slug.endswith("-to-png"):
            fallback_faq.append(
                {
                    "question": "Does PNG preserve image quality?",
                    "answer": "PNG uses lossless compression, so image quality stays intact during conversion.",
                }
            )

    faq_items = list(faq_items or tool_data.get("faq", []))
    existing_questions = {item.get("question", "").lower() for item in faq_items}
    for fallback_item in fallback_faq:
        if fallback_item["question"].lower() not in existing_questions:
            faq_items.append(fallback_item)

    if meta_overrides:
        seo_data.update(meta_overrides)

    if canonical_path is not None:
        seo_data["canonical"] = f"{PRODUCTION_BASE_URL}{canonical_path}"
        seo_data["og_url"] = seo_data["canonical"]

    page_sections = _build_tool_page_sections(tool_data)
    landing_context = None
    if slug == "mp4-to-mp3":
        landing_context = landing_page_builder.build_context(
            request,
            tool_data,
            faq_items=faq_items,
            canonical_path=canonical_path,
        )
        seo_data = landing_context["meta"]

    return templates.TemplateResponse(
        request=request,
        name="tool_page.html",
        context={
            "request": request,
            "locale": locale_data,
            "t": t,
            "title": seo_data["title"],
            "meta": seo_data,
            "seo": seo_data,
            "tool": tool_data,
            "faq": faq_items,
            "upload_form": tool_data.get("upload_form", {}),
            "related_tools": related_tools,
            "structured_data": seo_service.build_structured_data(
                request,
                tool_data,
                canonical_path=canonical_path,
            ),
            "hero": page_sections["hero"],
            "benefits": page_sections["benefits"],
            "features": page_sections["features"],
            "supported_formats": page_sections["supported_formats"],
            "how_to_use": page_sections["how_to_use"],
            "use_cases": page_sections["use_cases"],
            "about_formats": page_sections["about_formats"],
            "cta": page_sections["cta"],
            "landing": landing_context,
        },
    )


@router.get("/{slug}", response_class=HTMLResponse)
async def tool_page(request: Request, slug: str):
    return await render_universal_tool_page(request, slug, canonical_path=f"/tools/{slug}")
