import json
from pathlib import Path

base_dir = Path('app/data/converters')
format_labels = {
    'bmp': 'BMP',
    'jpg': 'JPG',
    'jpeg': 'JPEG',
    'png': 'PNG',
    'webp': 'WEBP',
    'pdf': 'PDF',
    'word': 'Word',
    'docx': 'DOCX',
    'mp4': 'MP4',
    'mp3': 'MP3',
    'ico': 'ICO',
}

category_content = {
    'image': {
        'features': [
            {'title': 'High-quality output', 'text': 'Preserve the visual quality of your files while converting between common image formats.'},
            {'title': 'Fast workflow', 'text': 'Upload, convert, and download in a few quick steps without installing software.'},
            {'title': 'Secure processing', 'text': 'Your files are handled securely and the result is ready to use immediately.'},
        ],
    },
    'audio': {
        'features': [
            {'title': 'Clear audio conversion', 'text': 'Convert audio files while keeping the sound quality as clear as possible.'},
            {'title': 'Quick media workflow', 'text': 'Switch between media formats quickly for editing, sharing, or storage.'},
            {'title': 'Reliable file output', 'text': 'Receive a ready-to-use result without installing extra tools.'},
        ],
    },
    'video': {
        'features': [
            {'title': 'Fast media conversion', 'text': 'Convert video files quickly while preserving the original content.'},
            {'title': 'Simple export steps', 'text': 'Prepare media for editing, sharing, or archiving in just a few steps.'},
            {'title': 'Stable output quality', 'text': 'Get a dependable output file that is ready for download.'},
        ],
    },
    'document': {
        'features': [
            {'title': 'Editable document output', 'text': 'Turn documents into a format that is easy to edit and reuse.'},
            {'title': 'Preserve structure', 'text': 'Keep the structure and core content intact during conversion.'},
            {'title': 'Fast document sharing', 'text': 'Export content quickly for collaboration and downstream workflows.'},
        ],
    },
}

for path in sorted(base_dir.glob('*.json')):
    with path.open('r', encoding='utf-8') as handle:
        data = json.load(handle)

    slug = data.get('slug') or path.stem
    if '->' in slug:
        source, target = slug.split('->', 1)
    else:
        parts = slug.split('-to-')
        source = parts[0] if len(parts) == 2 else (data.get('source') or 'file')
        target = parts[1] if len(parts) == 2 else (data.get('target') or 'file')

    source_label = format_labels.get(source, source.upper())
    target_label = format_labels.get(target, target.upper())
    category = (data.get('category') or 'general').lower()
    feature_content = category_content.get(category, category_content['image'])['features']

    data.setdefault('source', source)
    data.setdefault('target', target)
    data.setdefault('category', category if category in category_content else 'image')
    data.setdefault('active', True)
    data.setdefault('popular', True)
    data.setdefault('featured', False)

    data['hero'] = {
        'eyebrow': 'Converter tool',
        'title': f'Convert {source_label} to {target_label} Online Free',
        'description': data.get('description') or f'Convert {source_label} files to {target_label} online for free.',
        'panel_label': 'Ready to convert',
        'panel_title': f'Upload a {source_label} file and receive a {target_label} result in seconds.',
    }

    data['features'] = [
        {'title': item['title'], 'text': item['text']}
        for item in feature_content
    ]

    data['supported_formats'] = {
        'input': [source_label],
        'output': [target_label],
        'description': f'{source_label} input, {target_label} output',
    }

    data['how_to_use'] = [
        {
            'title': 'Upload your file',
            'description': f'Select a {source_label} file from your device to start the conversion.',
        },
        {
            'title': 'Choose the output format',
            'description': f'Pick {target_label} as the result format and review the conversion options.',
        },
        {
            'title': 'Download the converted file',
            'description': 'Get your converted file immediately without installing extra software.',
        },
    ]

    data['about_formats'] = [
        {
            'title': f'What is {source_label}?',
            'text': f'{source_label} is the source file format used for this conversion workflow.',
        },
        {
            'title': f'What is {target_label}?',
            'text': f'{target_label} is the output format generated by this converter.',
        },
    ]

    data['cta'] = {
        'eyebrow': 'Ready to convert',
        'title': f'Convert {source_label} files to {target_label} in seconds',
        'text': 'Upload your file and receive a ready-to-use result instantly.',
        'primary_text': 'Convert now',
        'secondary_text': 'Read FAQs',
        'primary_href': '#converter',
        'secondary_href': '#faq',
    }

    seo = data.setdefault('seo', {})
    seo['title'] = seo.get('title') or f'{source_label} to {target_label} | Converigo'
    seo['description'] = seo.get('description') or f'Convert {source_label} to {target_label} Online Free'
    seo['keywords'] = seo.get('keywords') or f'{source_label.lower()} to {target_label.lower()}, converter'

    with path.open('w', encoding='utf-8') as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False)
        handle.write('\n')

print(f'Updated {len(list(base_dir.glob("*.json")))} converter files.')
